os: linux
dist: focal
language: python
python: 3.7
install:
- pip install importlib-metadata --upgrade
- pip install mkdocs-material==8.5.1
script:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 strategy: git
 repo: devops-frre/devops-frre.github.io
 target_branch: main
 token: $GITHUB_TOKEN
 local_dir: site
 on:
   branch: main
