language: python
install:
- pip list
- pip install importlib-metadata --upgrade
- pip list
- pip install mkdocs-material==7.1.0
script:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 repo: devops-frre/devops-frre.github.io
 target_branch: main
 github_token: $GITHUB_TOKEN
 local_dir: site
 on:
   branch: main
