site_name: MkOps
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: red
    language: es
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.expand
plugins:
  - search
copyright: Copyright &copy; 2021 Nelson Yaccuzzi
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nelsonyaccuzzi
      name: nelsonyaccuzzi on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/nelsonyaccuzzi
      name: nelsonyaccuzzi on GitHub

