site_name: MkOps

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: light-blue
      accent: indigo
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: light-blue
      accent: blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Bienvenido: index.md
  - Contenido: contenido.md
  - Práctica: 
    - Virtualización: practica/virtualization.md
    - Contenedores: practica/containers.md
    - Orquestación: practica/orquestation.md
    - CI/CD: practica/ci-cd.md
    - Bases de Datos: practica/dbs.md
  - Otros:
    - K8s - containerd: otros/kubernetes-containerd.md
    - K8s - CRI-O: otros/kubernetes-crio.md

plugins:
  - search
copyright: Copyright &copy; 2022 Nelson Yaccuzzi
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nelsonyaccuzzi/mkops
      name: nelsonyaccuzzi on GitHub

