site_name: MkOps
theme:
  name: material
  palette:
    # Light mode
    - deep purple: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light-blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.expand
plugins:
  - search
copyright: Copyright &copy; 2021 Nelson Yaccuzzi
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nelsonyaccuzzi
      name: nelsonyaccuzzi on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/nelsonyaccuzzi
      name: nelsonyaccuzzi on GitHub

