---
- name: Example
  hosts: localhost
  tasks:
    - name: Download Terraform
      connection: local
      ansible.builtin.get_url:
        url: https://releases.hashicorp.com/terraform/1.3.4/terraform_1.3.4_darwin_amd64.zip
        dest: /home/elon/terraform.zip
        mode: '0440'