FROM debian:stable-slim

RUN apt-get update && apt-get install wget -y && \
wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.7.0/flyway-commandline-9.7.0-linux-x64.tar.gz | tar xvz && \
ln -s `pwd`/flyway-9.7.0/flyway /usr/local/bin