apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  env1: "hola"
  env2: "true"
  env3: "3300"
  nginx.conf: |
    # DevOps 2022
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        server {
            listen       80;
            listen  [::]:80;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-cm
  template:
    metadata:
      labels:
        app: nginx-cm
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        env:
          - name: env1
            valueFrom:
              configMapKeyRef:
                name: nginx-conf
                key: env1
          - name: env2
            valueFrom:
              configMapKeyRef:
                name: nginx-conf
                key: env2
          - name: env3
            valueFrom:
              configMapKeyRef:
                name: nginx-conf
                key: env3
        volumeMounts:
        - name: config
          mountPath: /etc/nginx
      volumes:
        - name: config
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf