apiVersion: v1
kind: Secret
metadata:
  name: nginx-conf
type: Opaque
data:
  username: ZWxvbg==
  password: bXVzaw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-secret
  template:
    metadata:
      labels:
        app: nginx-secret
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        env:
          - name: username
            valueFrom:
              secretKeyRef:
                name: nginx-conf
                key: username
          - name: password
            valueFrom:
              secretKeyRef:
                name: nginx-conf
                key: password